# 双相机配置示例
# 为每个相机配置不同的命名空间和序列号

/camera_left:
  ros__parameters:
    camera_name: camera_left
    camera_sn: "00000001"  # 请替换为实际的相机序列号 (通过 list_cameras_launch.py 查看)
    
    # Image resolution (0 for camera default)
    image_width: 0
    image_height: 0
    
    # Camera parameters
    exposure_time: 5000.0  # Exposure time in microseconds
    gain: 8.0              # Gain value (0~16)
    frame_rate: 10.0       # Frame rate in fps
    
    # Image processing
    flip_image: false

/camera_right:
  ros__parameters:
    camera_name: camera_right
    camera_sn: "00000002"  # 请替换为实际的相机序列号 (通过 list_cameras_launch.py 查看)
    
    # Image resolution (0 for camera default)
    image_width: 0
    image_height: 0
    
    # Camera parameters
    exposure_time: 5000.0  # Exposure time in microseconds
    gain: 8.0              # Gain value (0~16)
    frame_rate: 10.0       # Frame rate in fps
    
    # Image processing
    flip_image: false
