object_detection_openvino_node:
  ros__parameters:
    # Detection mode
    mode: "armor"
    
    # Model inference parameters
    input_width: 640
    input_height: 384
    score_threshold: 0.5
    nms_threshold: 0.4
    
    # Model file paths (update these paths according to your setup)
    xml_path: "./src/object_detection_openvino/config/openvino/Katrin.xml"
    bin_path: "./src/object_detection_openvino/config/openvino/Katrin.bin"
    device: "CPU"  # Options: CPU, GPU, MYRIAD, etc.
    
    # Topic names
    image_topic: "/camera_left/image_raw" # the topic subscribed to publish camera image  e.g., "/camera/image_raw"
    detection_topic: "/detector/target2d_array" # the topic to publish detection results
    debug_image_topic: "/detector/debug_image" # the topic to publish debug visualization image
    
    # Debug options
    publish_debug_image: true # set to true to publish debug image with bounding boxes and labels
    
    # Topic settings are handled in launch file remappings